version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=file:/app/dev.db
    restart: always
    volumes:
      - ./dev.db:/app/dev.db
