// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import fs from "fs";
import path from "path";

// Fallback to read .env file locally without requiring 'dotenv' which breaks Docker standalone
if (!process.env.DATABASE_URL) {
  try {
    const envPath = path.resolve(process.cwd(), '.env');
    const envFile = fs.readFileSync(envPath, 'utf8');
    const dbUrlLine = envFile.split('\n').find(line => line.trim().startsWith('DATABASE_URL='));
    if (dbUrlLine) {
      process.env.DATABASE_URL = dbUrlLine.split('=', 2)[1].trim().replace(/^"|"$/g, '');
    }
  } catch (e) {
    // Ignore error, assume running in production docker
  }
}

export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
};
